data:
  block_size: 512 # Equal to hop_length
  cnhubertsoft_gate: 10
  duration: 2
  encoder: hubertsoft # 'hubertsoft', 'vec256l9', 'vec768l12'

  encoder_hop_size: 320
  encoder_out_channels: 256 # 256 if using hubertsoft 768 if using 'vec768l12'
  encoder_sample_rate: 16000
  extensions: # List of extension included in the data collection
  - wav
  sampling_rate: 44100
  training_files: dataset/filelists/train_colab.txt
  unit_interpolate_mode: nearest
  validation_files: dataset/filelists/val_colab.txt
device: cuda
env:
  expdir: logs/44k/diffusion
  gpu_id: 0
infer:
  method: 'dpm-solver++' # 'pndm' or 'dpm-solver' or 'ddim' or 'unipc' or 'dpm-solver++'
  speedup: 10
model:
  k_step_max: 0 # must <= timesteps, If it is 0, train all
  n_chans: 512
  n_hidden: 256
  n_layers: 20
  n_spkr: 1 # max number of different speakers
  timesteps: 1000
  type: Diffusion
  use_pitch_aug: true
spkr:
  sza_singing: 0
train:
  amp_dtype: fp32
  batch_size: 48
  cache_all_data: true
  cache_device: cpu
  cache_fp16: true
  decay_step: 1000
  epochs: 1000
  gamma: 0.5
  interval_force_save: 5000
  interval_log: 10
  interval_val: 80
  lr: 0.0001
  num_workers: 4
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: model_dir/nsf_hifigan/model_nsf_hifigan.pt
  type: nsf-hifigan
