wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692297080.776659
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.9
      5: 0.15.8
      8:
      - 5
